sudo: required

language: java
jdk: oraclejdk8

Services:
  - docker

env:
  global:
    - secure: "Ngb8Mzyoy1ZNpnY0LbmrZwFs80mk9U3ZT1vY9eBJMNNnUG27GxhaMfU+Vj4usXlqaiY6k4huy3lDzjvT/2+tT9Fw0YYeTRcoP1No58kEZ5WtD/tzrXOzZ4SqmN0Mfiuf53tZaToHMpDjqkEVpEKmt2s2/lKvUy0BYkxeclox6idaL6X1MK40LD0BcXugVZSMD6xo17mpDmdeobeTS3Yiwq/eKPl6GASwhNWREfK6pXm+4HMcWVSa8aoKRyFMGmkRqcGV4inPIWCX5BW0qWFFlLpHmp3mW3mQ+fbcS60wylMLY7/WwrMIARd/CzWyKzBvH+ocn9oPs3aB19+k292ukKDrVhv2g7WYl4we732FxjaKO2hX2HzX6lf8BLUTioYdWPnKK64u0ig6fABkoYVE4uO4LXNomjzHGZ8oGnFxD3x1EE0bW0+bXbi5uzBhBJXEVWK3x5aZQ1eILzNQYJn9gn0xUZy4b2O8q5I7TLIZYHGWqo/ILMF3ZCaLDtqRKKRUk6x0ukGJKEXaPws1XxvbixKupAji+Lqxh/W30fABeQjsYsGO87s6aTLmmk35sMTCUX+CJoVNN+6tAXYBQPdmBsimiCSUZh1dhaFSegNQAo4MD5Tbc6ddNo9JFQSnRLsvEdbeTAFEavd2nA88CIrV611j0ulLWZbLgHyasasyPS0=" # DOCKER_USER
    - secure: "Cqgh3EbwvRNlR76+xGYf8FT5h4h1BOM9gsTJnYb7mItg+xIiEzbp+U9HB4PG1cqZ7aNVTKzdyswvIxzsasDbC9dERmfbAzqs3y0CUxbTipl9PT76LNFx5eP2pDCu7VmKGyz6zdeXQqlDH3fuF4O0R/0bhM1/9h8Bo2Ruaq7ELwvMDe/lPPf14By7U7mbw2mKFZGlI2QZDJMmOP9Bj6js0na7NWgekMhzfdlSOOovpHrNxilzZRdT/6t9F+WrrJf/ps/GHIXHVpZAQpyj3AQAelYBQW/LkTkWyVjNEx9FNBN91VFbWzVTrB06xafAb6dw70pUXu6TpHX4yHepPBRO3xl4kxYSOQOiUDE05PUcfE+++P8hIzhyh+TnZC8qrpNpfscKDgyqfD58PNKbRRZFLg9Zt9HIv85+iH4ebT3Tv5nzAzW6xGRC6pPIanGpsVUez9Su2UmNyPBT2prXEuwm/OyUM4imHa6VJzRcSJpADoTOFjj+5NDptYpYKiqqw7Pw6M917AsjrWoq4H6lIVtXRK9UFrZO67bYpsCxZqgBB8lGUGsbThCc1eMwnPwtgZ8ojwYW1R0MYgeFhivGDSlh+qav7s6jem4ylL2CYyBMngVFii4zdFK95N/IQjJvAo8JyVwa+vjEMqMvwuqsWeNKL5edVYAVSrhdC8+IQu3wsys=" # DOCKER_PASS
    - secure: "kr62JEk93GxZIMekVLTnKjoK8/mwZd22qAfmzoCauxJ6wtGCGyMcBNSjPfzEnz4BC7riNywcQtOThepE2KZZeisvisLo1VfJmSW2/5TBcqJ+SSOHQurEfpNCziUzkwzPwLTqA4BBuV/dGoeHRnBPiDxokjxW6cISY9Vbu8lz35VSMZ8MsiNZc2ws1pNPEzXWEBVFbnlmJmoT4q1tWri4Y4nGCwEORctsgFIk/eIZhBpds3zStYr3ZJq4KZKF9pWkxrvNlpKZ5q4memy8fqm0ZrE5AVh+EyVmE23NfQPvLXZPUU6IubzgtGcA8TXdYu5pbbt7fkx5J3/gtYzIYByWdO8QPd6beUZPF0urOW6c7oTFViyxTqroMeXdmgWdwmJmVSEL7r9H+6nLTni2VxPLmSJDV14a3XBhLsjjjNbTz3/eHEtOZs+usdt0whYDj6VVhanHXRkoE8b710UAz1Nb+PU5FS3aYTFP9OXvUX9GcJA71l6+ytsz040bajPTTtuyAsR/yDOpjCBqQW7L9gLM+o64/cNisiNF5yHbe5ZS17dsqcnLzewliihBli9Ck6CX2K2AAGr++o2fIzMcG05cfP1Tx3c1deyFxkx4zT2+GBJlgNt0+SecEN8qSIRB3VwwZU0vazRLdpIVR3R3BXJ41hF+QtxfnrkMNKEk1tcgYNg=" # DOCKER_EMAIL
    - secure: "lBhRAIFEo32uVUUA4wq2o3Uq21L820q/sO59Is/rzMLs7KDJpwXrDrc5K+nGeA7l+KzJUUYbV7R5Pre6DYGQzpbPkMT+vbfrmCGBpCKA51l1Q18VKLYCxisesgNSm3xhwArQiBDPsQKsnBYtzVDI8PtQpI5Z4KjucRecy3YwULjLf6phyAJdLHuSoXSHB/vRzh1JFiS7LanbWJPkpQCALm1Xit+BLV0TE2k+uiRUIWQachAAdRZOpsVR6IerlCRbeW/VJTa5IevNpDWVtBmm+iY31G/kQ3mkBxCCQ1RNfZWinFTEdYmI+kU0GKFAoJJMNxmV06NYvx3e8+XYQLeAS5wAC62Ghg1laZhccxpZYR/d6t4lQwrcd6tOOvzFB/1zLzQoe64FyaPQy42Tnvj1k9T6eRwoILSVfFAyEMHO/jZQV+2VQqFIZjok+CRjIb4x3saZH0JC13b9jY8eHrv9XiMbRrlxdgJrj8P2Q5aKHO40S520sZqwa3GNPCmNYvr8JoVYo9O/z5+KyjGuPYfxwa8DzLpG/Uje7QrGjM8xFjRpyl8OdT6ajel+2uy/qu15SUvBJtc05fo70GznL44PB2adqsbwRzb56jrPRjPx6FopV3gkGFr6FPBGBA/waB8Ul0fNt9y1QzcdJ/SPlawSUTR0uanOOT+XXESm6+RaSNM=" # CODECOV

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - docker login -u $DOCKER_USER -p $DOCKER_PASS

  #TAG
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`

  #INVENTORY SERVICE
  - export INVENTORY_SERVICE=matiasdynia/ecommerce-inventory-service
  - docker build -t $INVENTORY_SERVICE:$TAG ./inventory-service
  - docker tag $INVENTORY_SERVICE:$TAG
  - docker push $INVENTORY_SERVICE

  #CLIENT SERVICE
  - export CLIENT_SERVICE=matiasdynia/ecommerce-client-service
  - docker build -t $CLIENT_SERVICE:$TAG ./client-service
  - docker tag $CLIENT_SERVICE:$TAG
  - docker push $CLIENT_SERVICE

  #SHOPPING SERVICE
  - export SHOPPING_SERVICE=matiasdynia/ecommerce-shopping-service
  - docker build -t $SHOPPING_SERVICE:$TAG ./shopping-service
  - docker tag $SHOPPING_SERVICE:$TAG
  - docker push $SHOPPING_SERVICE

  #API ECOMMERCE
  - export API_ECOMMERCE=matiasdynia/api-ecommerce
  - docker build -t API_ECOMMERCE:$TAG ./api-ecommerce
  - docker tag API_ECOMMERCE:$TAG
  - docker push API_ECOMMERCE

  #CONFIG SERVER
  - export $CONFIG_SERVER=matiasdynia/ecommerce-config-server
  - docker build -t $CONFIG_SERVER:$TAG ./config-server
  - docker tag $CONFIG_SERVER:$TAG
  - docker push $CONFIG_SERVER