version: '3'
services:
  mysqldb:
    image: mysql:5.7
    container_name: inventoryservicedatabase
    ports:
      -  "3306:3306"
    environment:
      MYSQL_DATABASE: "inventory"
      MYSQL_USER: "matias"
      MYSQL_PASSWORD: "matias"
      MYSQL_ROOT_PASSWORD: "matias"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"